---
title: 'STATS 744: Homework 5'
author: "Steve Cygu"
date: "`r format(Sys.time(), '%d %B %Y ')`"
output:
  html_document: default
  pdf_document: default
---





```{R opts, message = FALSE}
# Set global options
knitr::opts_chunk$set(echo = TRUE
   , warning = FALSE
   , message = FALSE
#  , fig.width = 10
#  , fig.height = 8
   , results = "asis")
options(width = 12)

## Install or load required packages
library(dplyr)
library(tibble)
library(DT)

library(reshape2)
library(lme4)

library(ggplot2)
theme_set(theme_bw() + 
	theme(panel.spacing=grid::unit(0,"lines")))

library(ggpubr)

## Source function from funs dir
source("funs/globalFuns.R")
```



## About the problem data

In 2015, [Arifu Kenya](https://www.arifu.com/) conducted a pilot study of about `4000` small holder farmers in Kenya. In this pilot they conducted two experiments to test the best language to increase uptake and usage of their short messaging service (SMS) platform for about 5 months:

- They randomly assigned learners to receive two types of SMS invitation messages
- They randomly assigned learners who engaged to interact with "Narrative" vs. "Fact-Based" versions of content

- Each `in-coming` and `out-going` message has its own column. All interactions are tagged with a code that indicates which versions learners engaged with. The number / letter at the end of the `program_code` indicates what invitation messaging they received and which content they accessed. i.e.
	- MAIZE1 = Invitation 1 \& Fact-Based Content
	- MAIZE1-N = Invitation 1 \& Narrative Content
	- MAIZE2 = Invitation 2 \& Fact-Based Content
	- MAIZE2-N = Invitation 2 \& Narrative Content

- See content map [here](Maize_Content_Map.pdf)

The variables in the dataset are described in the table below:

Variable	|	Description
--------	|	-----------
user_id	|	User identifier
program_code	|	Invitation messaging
message_in	|	User typed in message
message_out | System generated message
origin | Either user or system
created_at	| Date created

## Aim

- Investigate the effect of language on the uptake and usage of their SMS platform

## Data manipulation


```{R}

## Create output directory
createDir(dirname = "HW5", dirpath = ".")

## Load data
raw_df <- read.csv("arifu_sms_data.csv")
str(raw_df)
```

- Generate new column `message_in_out` to sequencially show the sent and received SMS and then spread by `origin` and fill by `message_in_out`  to have sent-received SMS side by side.

```{R}
working_df <- (raw_df
	%>% filter(!is.na(user_id)|user_id!="")
	%>% mutate_at(c("message_in", "message_out"), as.character)
	%>% mutate(message_in_out = ifelse(message_out=="", message_in, message_out))
	%>% group_by(origin)
	%>% mutate(cn=1:n()
		, created_at = as.POSIXct(as.character(created_at),  format = "%Y-%m-%d %H:%M:%S")
	)
	%>% ungroup()
	%>% data.frame()
	%>% reshape2::dcast(user_id + program_code + created_at + cn~origin, value.var = "message_in_out")
)
```

**Manipulations**

- Create user `language` variable i.e., the system sent SMS with the following `program_code` tags:
	- Swahili: *MAHINDI
	- English: *MAIZE
- Create `content` variable. Each language could have Fact Based or Content based content:
	- See definition in `About data`
- Calculate amount of time, `duration`, taken by the respondent to respond to all SMS
- Calculate the total number of replies sent by each users.
- The text which starts with "I'm Arifu. Reply..." or "Naitwa Arifu. Jibu kwa..." triggers the conversion (first SMS from Arifu) so time difference starts from that and it has `duration = 0`. All the trigger cases are dropped. 
- Count the number of SMS `num_sms` (number sent) by each respondent (count sms loop per respondent) after the trigger per `user_id` per `program_code`
- Gather all the calculated information per respondent

```{R}
#difffunc <- function(x){
#	diffs <- numeric(length(x))
#	for (i in 1:length(x)-1){
#		diffs[i] <- ifelse(i==1, 0, difftime(x[i+1], x[i], units = "mins"))
#	}
#	return(diffs)
#}
working_df <- (working_df
	%>% mutate(language = ifelse(grepl("^MAIZE", program_code), "English", "Swahili")
		, content = ifelse(grepl("-N$", program_code), "Narrative based", "Fact based")
	)
	%>% group_by(user_id, program_code)
	%>% mutate(duration = difftime(max(created_at), min(created_at), units = "mins"))
	%>% filter(!grepl("^Naitwa Arifu. Jibu kwa|I'm Arifu. Reply with a", system))
	%>% mutate(num_sms = n())
)

# Select key calculated variables foe summary
working_df <- (working_df
	%>% ungroup()
	%>% select(c("user_id", "language", "content", "num_sms"))
	%>% mutate(lang_content = paste0(language, " - ", content))
	%>% distinct()
)
datatable(head(working_df), rownames = FALSE)
```

**Observation**

- One user could receive:
	- both swahili and english content
	- both fact-based and narrative-based
	- The languages can either be fact based or narrative-based

**Visualization**

- We sum the number of replies by each user and then visualize.
- From the plot below, in general, English content have less replies as compared to Swahili content. This is the same to Fact based versus Narrative based content (less replies for Fact based). In addition, a Swahili Narrative based content is more likely to have less replies as compared to English based narative.




```{R}
plot_df <- (working_df
	%>% select(-lang_content)
	%>% group_by(user_id)
	%>% mutate(num_sms2 = sum(num_sms))
	%>% distinct()
)
base_plot <- (ggplot(plot_df, aes(x = num_sms2, fill = content))
	+ geom_histogram(alpha=0.5, stats= "dodge")
	+ facet_wrap(~language)
	+ labs(x = "Number of SMS replied to by farmer"
		, y = "Count"
		, fill = "Content"
		, colour = "Type of content"
	)
)
print(base_plot)
```

**Modeling**

- Each user could respond to more than one program (lang_content/program_code). So, we aggregated our data to number of sms per user per language per content type.
- We fit a poisson generalised linear mixed effect model to estimate the effect of language and content type on number of replies (`num_sms`) with a `user_id` (farmer) random intercept.

```{R}
sms_model <- glmer(num_sms ~ language*content + (1|user_id)
	, data = working_df
	, family = poisson(link = "log")
)
```

## Results

**Fixed and random effects**

- Only a sample of $15$ individuals are shown in random effect plot
- From the Figures below:
	- There is an individual level variation in regards to language and type of content they receive the SMS through on number of replies they give
	- There is a positive effect of deliveling a Swahili narrative based content on number of replies the farmers will give
	- However, there is a negative effect of delivering Swahili SMS and narrative based, individually, on the number of responses made by the farmers


```{R}
coefs_df <- (broom.mixed::tidy(sms_model, effects=c("fixed", "ran_pars", "ran_vals"), conf.int = TRUE)
	%>% mutate(term = factor(term, levels = unique(term)))
	%>% mutate(term = reorder(term, estimate))
)
feff_df <- (coefs_df
	%>% filter(term != "(Intercept)")
)

# Fixed effects
pos <- ggstance::position_dodgev(height=0.5)
feff_plot <- (ggplot(feff_df, aes(x = estimate, y = term))
	+ geom_point(position = pos)
   + ggstance::geom_linerangeh(aes(xmin = conf.low, xmax = conf.high), position = pos)
   + scale_colour_brewer(palette="Dark2"
		, guide = guide_legend(reverse = TRUE)
   )
   + geom_vline(xintercept=0,lty=2)
   + labs(x = "Estimate", y = "")
	+ theme(text = element_text(size = 13))
)

# Random effects
n_indiv <- 15
reff_df <- (coefs_df
	%>% filter(term == "(Intercept)" & effect == "ran_vals")
	%>% sample_n(n_indiv)
	%>% mutate(term = level)
)
reff_plot <- feff_plot %+% reff_df
```

**Fixed effect**

```{R, echo = FALSE}
feff_plot
```

**Random effect**

```{R, echo = FALSE}
reff_plot
```

## Conclusion

- Arifu should embrace a Kiswahili with a Narrative based plotform inoder to get more replies from the farmers.

